[package]
name = "oneopoly"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
oneopoly = "0x0"

[environments]
devnet = "826b0c22"
